language: objective-c
before_install: gem install cocoapods slather -N
script: 
	- pod install
	- xctool -project MyBrowseOverflow.xcodeproj -scheme MyBrowseOverflowTests -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean build test
after_success: slather
